<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE bank [
    <!ELEMENT bank (accounts, customers, customer_accounts)>
    <!ELEMENT accounts (savings_accounts, checking_accounts)>
    
    <!ELEMENT savings_accounts (savings_account+)>
    <!ELEMENT savings_account (balance)>
    <!ATTLIST savings_account 
        id ID #REQUIRED 
        interest CDATA #REQUIRED>
    
    <!ELEMENT checking_accounts (checking_account+)>
    <!ELEMENT checking_account (balance)>
    <!ATTLIST checking_account id ID #REQUIRED>
    
    <!ELEMENT balance (#PCDATA)>
    
    <!ELEMENT customers (customer+)>
    <!ELEMENT customer (name, address)>
    <!ATTLIST customer id ID #REQUIRED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    
    <!ELEMENT customer_accounts (customer_account+)>
    <!ELEMENT customer_account EMPTY>
    <!ATTLIST customer_account 
            customer_id IDREF #REQUIRED
            account_id IDREF #REQUIRED>
]>



<bank>

  <accounts>
    <savings_accounts>
      <savings_account id="a1" interest="0.03">
        <balance>2500</balance>
      </savings_account>
      
      <savings_account id="a2" interest="0.03">
        <balance>15075</balance>
      </savings_account>
    </savings_accounts>
    
    <checking_accounts>
      <checking_account id="a3">
        <balance>4025</balance>
      </checking_account>
      <checking_account id="a4">
        <balance>-125</balance>
      </checking_account>
      <checking_account id="a5">
        <balance>325</balance>
      </checking_account>  
    </checking_accounts>
  </accounts>
  
  <customers>
    <customer id="c1">
      <name>Ben Richerdson</name>
      <address>Park Drive 2</address>
    </customer>
    <customer id="c2">
      <name>Marc Wretcher</name>
      <address>Mill Drive 75</address>
    </customer>
    <customer id="c3">
      <name>Angel Steady</name>
      <address>Lake Sight 15</address>
    </customer>
  </customers>
  
  <customer_accounts>
    <customer_account customer_id="c1" account_id="a2"/>
    <customer_account customer_id="c1" account_id="a3"/>
    <customer_account customer_id="c2" account_id="a4"/>
    <customer_account customer_id="c3" account_id="a1"/>
    <customer_account customer_id="c3" account_id="a5"/>
  </customer_accounts>
  
</bank>
